### PR TITLE
Adding my solution.

### PR DESCRIPTION
**Pull request by Paul-W-Saltzman**

### CODE REVIEW

**Comment by Paul-W-Saltzman** [comment]
All errors are just the read me file or the migrations.

**Comment by stevietv** [comment]
Hi @Paul-W-Saltzman - before this is picked up for review I would like to comment that its missing an ExerciseService class

the Controller should call the Service
the Service then should call the Repository

in this project they will seem empty, like its just passing things about as a lot of the validation is done in the front end
in a real project the service would take all the input from the controller, and manipulate it (checking it against business logic, forming it into uniform DTOs etc) into a form to pass to the repository.

can you implement this step?

**Comment by Paul-W-Saltzman** [comment]
Hey thanks for taking the review.   I'm getting ready to leave for vacation, I'll be back on the 10th.   I can try and take a look while I'm on vacation, but I don't know how far I'll get.   Honestly I can't tell you how much difficulty this project has been giving me.  I've watched so many videos and articles.  I could use some help if you would be willing.   I hate to come begging, but could you help me figure this pattern out when I get back.  Maybe a discord call or something?  I realize it's a big ask so if you would prefer not to I get it.

**Comment by Paul-W-Saltzman** [comment]
Made the requested changes.

**Comment by stevietv** [comment]
thanks for the update, this is exactly what was needed! ✅

**Pull request merged**
