### PR TITLE
Completed the project

### PR DESCRIPTION
**Pull request by kalsson**

### CODE REVIEW

**Review by Doc415 — COMMENTED** [review]
Hey pal,

when try to add exercise i dont know the correct format app requires so it does not add
the input. Can you add a notifier for correct format?
image


In the requirements of the project, there should be a userinput class to handle front end
controller should only be the entry point of backend :)
Seperate class should handle user input and views 

waiting for the update , good luck :)

**Review by Doc415 — CHANGES_REQUESTED** [review]
Details in comment

**Comment by kalsson** [comment]
Hey buddy,

Thanks, I will check it 😉

**Comment by kalsson** [comment]
Hey again @Doc415 

Check it out now mate 😁

**Review by Doc415 — CHANGES_REQUESTED** [review]
image
😬

**Comment by kalsson** [comment]
q

> image 😬

Haha, whaaaat! I will check it 🤣

**Comment by kalsson** [comment]
My god mate, this was a big problem that ChatGPT had to help me fix. 🤣

**Comment by kalsson** [comment]
I'm sooooo done with this console projects, I hate them but I know it is good fundamental practise!

**Review by Doc415 — APPROVED** [review]
Good to go :)

**Pull request closed without merging**
