### PR TITLE
completed exercise tracker

### PR DESCRIPTION
**Pull request by stevietv**
This one was a tricky one to understand the requirements on. I wasn't sure what exactly the requirements were and when looking at the tutorial links it sort of became clear.

As I understand it now, the work related to the database is done in the repository instead of in the controller as before.

In this new case the program passes the work to the controller, which passes the work down to the service and the service passes this onto the repository.
This way we could change the way the repository does it work (i.e. different db format) and the rest would stay intact.
This is my understanding :)

### CODE REVIEW

**Comment by stevietv** [comment]
Looking at this again, and having watch a video on Youtube I think I may have overcomplicated things a bit?

Right now my ExerciseController class passes calls to the ExerciseService class, however this does nothing and just passes them through to the ExerciseRepository class where the work is done.

Instead I think I should be having the ExerciseController pass its calls to the ExerciseService class, and let this class do the work whilst implementing the repository.

| Submitted | Improved? |
|--------|--------|
| IExerciseRepository| IExerciseRepository|
| ExerciseRepository : IExerciseRepository| ExerciseService : IExerciseRepository|
| IExerciseService| |
| ExerciseService : IExerciseService| | 

looking forward to hearing your feedback here @TheCSharpAcademy

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@stevietv Your original solution was the correct one. I think the confusion stems from the fact that this is a small project and the service is redundant, but in a bigger project a service would grab data from different repositories and potentially different microsservices/apis. So it would be incorrect to inherit from a single IRepository. I'll make modifications to the requirements to make this separation more clear.

image

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@stevietv Your original solution was the correct one. I think the confusion stems from the fact that this is a small project and the service is redundant, but in a bigger project a service would grab data from different repositories and potentially different microsservices/apis. So it would be incorrect to inherit from a single IRepository. I'll make modifications to the requirements to make this separation more clear.

image

**Comment by stevietv** [comment]
changes are reverted :D

**Comment by TheCSharpAcademy** [comment]
@stevietv Good stuff, thanks for resubmitting. I do need to revamp the requirements, as at the moment it's just a bunch of layers 😆🤔

**Pull request merged**
