### PR TITLE
CodeReviews.Console.ExercisTracker.samggannon.PR

### PR DESCRIPTION
**Pull request by samggannon**

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @samggannon 

Thanks for your submission, Great work on implementing the Repository Pattern and showcasing the two different options.
There's a few things that need to be fixed up:

* When editing an end time to be before a start time the save of the data will cause a crash. You should be validating end times also on edit.
* Currently your not using any dependency injection at all, which is a requirement of the project. At the moment you create new instances of your controller, service and repo every time they are used.

**Comment by samggannon** [comment]
I think i figured out the Dependency Injection container. However after a lot trial and error, I noticed there was some tight coupling in my code. A common solution seemed to be implementing the FactoryPattern side by side with the RepositoryPattern, but it seemed out of scope for the focus of this project.

**Comment by TheCSharpAcademy** [comment]
@stevietv What's the status here? 🤓

**Comment by stevietv** [comment]
> @stevietv What's the status here? 🤓

@TheCSharpAcademy - I sent you a discord message 10 days ago asking for your input

**Comment by stevietv** [comment]
Hey @samggannon - I had a discussion with Pablo, and this is NEARLY there!
He gave the tip to say that its not handy to use Singleton services with stateful dependencies like EFCore:

image


It'd be great if these were updated to scoped to finalise this.

**Comment by stevietv** [comment]
thanks for the tweaks! ✅ Nice work!!

**Review by stevietv — APPROVED** [review]

**Pull request merged**
