### PR TITLE
CodeReview-ExerciseTraker-ConsoleProject

### PR DESCRIPTION
**Pull request by lonchanick**
Hello!

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@lonchanick Hello did you submit the project in the platform? 🤔🤔😁

**Comment by lonchanick** [comment]
Sorry totally forgot .. in a minute send the link

**Comment by TheCSharpAcademy** [comment]
@lonchanick I'm going to approve because you understood the concept of repository pattern, but currently I can't add comments to sessions, I can't insert a record with a different date, and I can't update a record 😟. When I choose update I get this: 
image

**Comment by lonchanick** [comment]
Hey! Sorry next time I'm going to spend more time on details :) 
Thanks!

**Pull request closed without merging**
