### PR TITLE
Complete exercise tracker

### PR DESCRIPTION
**Pull request by wkktoria**
I've completed only first challenge, there is no different branch, but some methods in [ExerciseRepository](https://github.com/wkktoria/CodeReviews.Console.ExerciseTracker/blob/222988a3fbc4c06e858c159a48835b2a47a23df4/ExerciseTracker.wkktoria/ExerciseTracker.wkktoria/Data/Repositories/ExerciseRepository.cs) use Entity Framework and the rest of them use Dapper.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@wkktoria Thanks for submitting! Were you able to update entries? I'm getting this:

image

**Comment by wkktoria** [comment]
> @wkktoria Thanks for submitting! Were you able to update entries? I'm getting this:
> 
> image

I think I fixed this issue. :smile:

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@wkktoria Still not working in my end 🥺
image

Also I can only input the time without the 'tt', so it would be good to update the expected format:

image

**Comment by wkktoria** [comment]
> @wkktoria Still not working in my end 🥺 image
> 
> Also I can only input the time without the 'tt', so it would be good to update the expected format:
> 
> image

I updated expected time format.
I also did some changes with updating entries and it seems to work now. 😅

**Pull request merged**
