### PR TITLE
Project Finished

### PR DESCRIPTION
**Pull request by BBualdo**
This project's UI is almost copy-paste from Shifts Logger.

I'm not sure about Repository Pattern though. I was confused where I should put my validation, so I did it in controller.

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @BBualdo - I've taken a look over your project, and this is my general feedback:

* as a user, when choosing to edit an activity its annoying to have to enter ALL details again, perhaps an option for entering blank meaning keep that property the same could be nice
* Nice clean interface :)
* You maybe made it more complex for yourself treating it as a webapi and a ui project, this was ok all as one console project, but nice job challenging yourself here and enhancing your knowledge on the webapis

Regarding the repository pattern the correct setup:

- Controller: takes the input from the user and passes it through to the service
- Service: performs the business logic and validation and calls to the repository
- Repository: passes the data to and from the database

with this pattern you can: 
* change your user input system by only editing your controller
* change your logic or validation by only editing the service
* change your database access or type by only editing the repository

Whilst you've got the idea about splitting them out, you've mixed up Controller and Service naming. Do you want to have a go at refactoring them before I approve?

**Comment by BBualdo** [comment]
Okay, I was deleting other projects because I've seen that those are deleted in beginners console apps repos, but now I understand that it's only to avoid too much folders 😁 Won't do that again 😀

Sure, I will try to follow your advice, I will ping you on dc when I'm done

**Comment by BBualdo** [comment]
I created controller for taking user's input. But if I understand properly, should I validate user input (for example if date is incorrect format) in service layer? But that would cause issue that error appears when all inputs are taken 😅

**Comment by stevietv** [comment]
thanks! I'm gonna approve it as its certainly following the principles of Repository Pattern. 😸 

I think if you were to follow it to the tee then your ExercisesService in the Frontend UI wouldn't make contact directly to the API but would pass the prepared object to another repository service for further handling. in that case you could leave the object validation and preparation logic in the service and change the repository service if your api changed.

Its a tough principle to apply and grasp, and sometimes I'm also not sure if I grasp it entirely. Good job!
Some people even consider the dbSet from EF Core the repository and access that directly from the service.

**Comment by BBualdo** [comment]
That and other "Clean programming" principles will become natural over time 😁 Thank you!

**Pull request closed without merging**
